# Form implementation generated from reading ui file 'nomelator.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(227, 176)
        self.centralwidget = QtWidgets.QWidget(parent=Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout.addWidget(self.lineEdit_nome)
        self.label_sobrenome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sobrenome.setObjectName("label_sobrenome")
        self.verticalLayout.addWidget(self.label_sobrenome)
        self.lineEdit_sobrenome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_sobrenome.setObjectName("lineEdit_sobrenome")
        self.verticalLayout.addWidget(self.lineEdit_sobrenome)
        self.pushButton_unir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_unir.setObjectName("pushButton_unir")
        self.verticalLayout.addWidget(self.pushButton_unir)
        self.label__completo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label__completo.setObjectName("label__completo")
        self.verticalLayout.addWidget(self.label__completo)
        self.lineEdit_completo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_completo.setReadOnly(True)
        self.lineEdit_completo.setObjectName("lineEdit_completo")
        self.verticalLayout.addWidget(self.lineEdit_completo)
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Nomelator"))
        self.label_nome.setText(_translate("Janela", "Nome:"))
        self.label_sobrenome.setText(_translate("Janela", "Sobrenome:"))
        self.pushButton_unir.setText(_translate("Janela", "UNIR"))
        self.label__completo.setText(_translate("Janela", "Nome Completo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec())
