# Form implementation generated from reading ui file 'somador.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 142)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_v1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_v1.setObjectName("label_v1")
        self.gridLayout.addWidget(self.label_v1, 0, 0, 1, 1)
        self.lineEdit_v1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_v1.setObjectName("lineEdit_v1")
        self.gridLayout.addWidget(self.lineEdit_v1, 0, 1, 1, 1)
        self.label_v2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_v2.setObjectName("label_v2")
        self.gridLayout.addWidget(self.label_v2, 1, 0, 1, 1)
        self.lineEdit_2_v2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2_v2.setObjectName("lineEdit_2_v2")
        self.gridLayout.addWidget(self.lineEdit_2_v2, 1, 1, 1, 1)
        self.pushButton_somar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_somar.setObjectName("pushButton_somar")
        self.gridLayout.addWidget(self.pushButton_somar, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.label_total = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total.setObjectName("label_total")
        self.gridLayout.addWidget(self.label_total, 3, 0, 1, 1)
        self.lineEdit_total = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_total.setReadOnly(True)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.gridLayout.addWidget(self.lineEdit_total, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Somador"))
        self.label_v1.setText(_translate("MainWindow", "Valor 1"))
        self.label_v2.setText(_translate("MainWindow", "Valor 2"))
        self.pushButton_somar.setText(_translate("MainWindow", "SOMAR"))
        self.label_total.setText(_translate("MainWindow", "Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
